FROM node:latest AS build

WORKDIR /app

COPY ./ClientApp/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli

COPY ./ClientApp /app

RUN ng lint --force=true
RUN ng build --outputPath=dist --prod=true

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./Utils/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 443 80

ENTRYPOINT nginx -g "daemon off;"

